-- 코드를 입력하세요
SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH,'%Y-%m-%d') AS DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE NOT TLNO is NULL AND MONTH(DATE_OF_BIRTH) = "03" AND GENDER = 'W'
ORDER BY MEMBER_ID ASC;